#NumPy
NumPy adalah library python yang digunakan untuk bekerja dengan array. 

NumPy berfungsi dalam domain aljabar linier, transformasi fourier, dan matriks.

NumPy menyediakan tipe array N-dimensi, ndarray, yang menjelaskan kumpulan "item" dari tipe yang sama.

https://numpy.org/doc/stable/reference/index.html

In [38]:
# Import module numpy
import numpy as np
print(np.__version__)

1.21.5


Array

In [39]:
#contoh array 1D
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [40]:
#contoh array 2D
b = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
b

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [41]:
#contoh array 3D
c = np.array([[[1, 2], [2, 3]], [[3, 4], [4, 5]], [[5, 6], [6, 7]]])
c

array([[[1, 2],
        [2, 3]],

       [[3, 4],
        [4, 5]],

       [[5, 6],
        [6, 7]]])

In [42]:
d = np.arange(1,10,2)
d

array([1, 3, 5, 7, 9])

In [43]:
e = np.linspace(1,10,4)
e

array([ 1.,  4.,  7., 10.])

In [73]:
f = np.zeros((2,2))
f

array([[0., 0.],
       [0., 0.]])

In [45]:
g = np.identity(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
#Membuat array random dari 0 sampai 1
h = np.random.rand(2,3)
# bisa juga pakai h = np.random.random(size = [x,y])
h

array([[0.53783116, 0.62059007, 0.28588735],
       [0.67278648, 0.7087518 , 0.75042094]])

In [50]:
#Membuat array integer random 
h = np.random.randint(1, 10, size = [3,3])
h

array([[1, 1, 4],
       [5, 3, 3],
       [2, 8, 8]])

In [51]:
#Mendefinisikan array menggunakan fungsi dtype()
array = np.array([1, 2.5, 'lalat', True], dtype="str")
array

array(['1', '2.5', 'lalat', 'True'], dtype='<U5')

https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [52]:
#Mengubah tipe data menggunakan fungsi astype()
a.astype(float)

array([1., 2., 3.])

In [54]:
#Mengetahui karakteristik array menggunakan .shape, .size, .ndim, .dtype
print("shape: ", b.shape)
print('Datatype: ', b.dtype)
print('Size: ', b.size)
print('Num Dimensions: ', b.ndim)

shape:  (3, 3)
Datatype:  int64
Size:  9
Num Dimensions:  2


Indexing dan Slicing

Index memiliki tiga parameter, yaitu [start:stop:step] dimana indeks pertama dimulai dari nol dan diakhiri dengan n-1. 

Slicing menggunakan parameter seperti berikut [x :] atau [: x] atau [x : y] untuk array 1D

Sedangkan indexing dalam ndarray bisa menggunakan [x , y]

In [55]:
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x[-1]

9

In [57]:
x[0:7:2]

array([0, 2, 4, 6])

In [58]:
b[0, 2]

3

In [59]:
c[1:, :1]

array([[[3, 4]],

       [[5, 6]]])

In [60]:
#boolean index
y = b > 4
y

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

Operasi aritmatik : +, -, /, *, **

https://numpy.org/doc/stable/reference/arrays.html

In [61]:
a + 2

array([3, 4, 5])

In [62]:
a_list = [1, 2, 3]
a_list + 2

TypeError: ignored

In [63]:
b_list = [3, 2, 1]
a_list + b_list

[1, 2, 3, 3, 2, 1]

In [64]:
a * b

array([[ 1,  4,  9],
       [ 3,  8, 15],
       [ 5, 12, 21]])

Matriks

In [65]:
#manipulasi matriks
b[1,2] = 100
b

array([[  1,   2,   3],
       [  3,   4, 100],
       [  5,   6,   7]])

In [66]:
#transpose
b.transpose()
np.transpose(b)
b.T

array([[  1,   3,   5],
       [  2,   4,   6],
       [  3, 100,   7]])

In [67]:
#flatten matriks
c.ravel()

array([1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7])

In [68]:
#statistik
print("Mean value is: ", b.mean())
print("Max value is: ", b.max())
print("Min value is: ", b.min())
print("Min value is: ", b.sum())

Mean value is:  14.555555555555555
Max value is:  100
Min value is:  1
Min value is:  131


In [69]:
# tile dan repeat
print("tile: ", np.tile(a,3))
print("repeat: ", np.repeat(a,3))

tile:  [1 2 3 1 2 3 1 2 3]
repeat:  [1 1 1 2 2 2 3 3 3]


In [70]:
# ambil unique dan jumlahnya
unik, count = np.unique(b, return_counts=True)
print("Unik: ", unik)
print("Count: ", count)

Unik:  [  1   2   3   4   5   6   7 100]
Count:  [1 1 2 1 1 1 1 1]


#QUIZ

Fill in the blanks to make the factorial function return the factorial of n. Then, print the first 10 factorials (from 0 to 9) with the corresponding number. Remember that the factorial of a number is defined as the product of an integer and all integers before it. For example, the factorial of five (5!) is equal to 1*2*3*4*5=120. Also recall that the factorial of zero (0!) is equal to 1.

In [ ]:
def factorial(n):
    result = 1
    for x in range(1, ___):
        result *= x
    return result

for n in range(___, ___):
    print(n, factorial(n+1))

Given a list of filenames, we want to rename all the files with extension hpp to the extension h. To do this, we would like to generate a new list called newfilenames, consisting of the new filenames. Fill in the blanks in the code using any of the methods you’ve learned thus far, like a for loop or a list comprehension.

In [ ]:
filenames = ["program.c", "stdio.hpp", "sample.hpp", "a.out", "math.hpp", "hpp.out"]
# Generate newfilenames as a list containing the new filenames
# using as many lines of code as your chosen method requires.
newfilenames = [file.____('.hpp', '.h') for file in ___]

print(newfilenames)
# Should be ["program.c", "stdio.h", "sample.h", "a.out", "math.h", "hpp.out"]

Write a script that prints the first 10 cube numbers (x**3), starting with x=1 and ending with x=10.

In [ ]:
for x in range(___,___):
    print(x**3)